remote_theme: hydecorp/hydejack@v9.2.1
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate

future: true
paginate: 10
paginate_path: "/blog/page:num/" # ←【追加】/blog/ の中で正しくページ送りさせるために必須です

title: "sin1's studio" # ←【修正】記号（'）が含まれるため、全体をダブルクォーテーションで囲みました
description: "ロボットつくるよ"
lang: ja

url: "https://sin1.studio"
baseurl: ""
theme_color: "#1111aa"
permalink: /blog/:title/

author:
  name: sin1
  email: sin1+hp@sin1.studio
  social:
    twitter: https://x.com/sin1west 
    github: https://github.com/sin1n24
    YouTube: https://www.youtube.com/@sin1n24
    email: mailto:sin1@sin1.studio
    Blog: https://sin1n24.hatenablog.com/

data_social:
  youtube:
    name: YouTube
    icon: icon-youtube
  blog:
    name: Blog
    icon: icon-rss

menu:
  - title: 新着情報
    url: /index.html#新着情報
  - title: ロボット
    url: /index.html#ロボット
  - title: ハードウエア
    url: /index.html#ハードウエア
  - title: ソフトウエア
    url: /index.html#ソフトウエア
  - title: 企画
    url: /index.html#企画
  - title: Blog
    url: /blog/

favicon: /img/favicon.ico
accent_image: /img/bg-image.jpg

hydejack:
  date_format: "%Y年%m月%d日"
  dark_mode:
    dynamic: true
    icon: true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules/
  - _site/
  
copyright: "© 2025 sin1. All rights reserved."