remote_theme: hydecorp/hydejack@v9.2.1
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

title: sin1's studio
description: ロボットつくるよ
lang: ja

url: "https://sin1.studio"
baseurl: ""
theme_color: "#1111ff"

author:
  name: sin1
  email: sin1+hp@sin1.studio
  social:
    twitter: https://x.com/sin1west 
    github: https://github.com/sin1n24
    YouTube: https://www.youtube.com/@sin1n24
    email: mailto:sin1@sin1.studio
    Blog: https://sin1n24.hatenablog.com/

data_social:
  youtube:
    name: YouTube
    icon: icon-youtube
  blog:
    name: Blog
    icon: icon-rss      # 専用アイコンがないので電波マーク(RSS)で代用します

menu:
  - title: Projects
    url: /index.html#製作物
  - title: Planning
    url: /index.html#企画

    
favicon: /img/favicon.ico
accent_image: /img/bg-image.jpg

hydejack:
  dark_mode:
    dynamic: true
    icon: true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules/
